/*Create beach table*/
CREATE TABLE `marka_db`.`beaches` (
  `idbeaches` INT NOT NULL AUTO_INCREMENT,
  `b_name` VARCHAR(45) NULL,
  `b_img` VARCHAR(500) NULL,
  `b_location` VARCHAR(256) NULL,
  `b_desc` TEXT(900) NULL,
  PRIMARY KEY (`idbeaches`));


/*Adding Beach info*/
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Cape May', 'https://media.cntraveler.com/photos/5772c2054a3399cb31f9da9d/master/w_820,c_limit/cape-mayGettyImages-167782987.jpg', 'Cape May, NJ', 'Cape May is \"one of the prettiest beach towns\" on the Shore, rave our readers, thanks largely to the historic Victorian district and miles of manses. We also sneak away to Cove Beach, perfect for swimmers and kayakers, families and couples alike.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Asbury Park', 'https://media.cntraveler.com/photos/57714907c06bba921a97a0f9/master/w_820,c_limit/asbury-park-new-jersey-beach-GettyImages-499475083.jpg', 'Asbury Park, NJ', 'Asbury has truly been reborn, starting with its boardwalk stocked with high-end food trucks and stalls like you\'d find in Brooklyn or Austin; a chic new Asbury Hotel with one of the best rooftop bars in town; a thriving music scene born of the Boss; and dog-friendly beaches and \"Yappy hours.\" ');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Long Beach Island', 'https://media.cntraveler.com/photos/5772c206558ff1e22af127d2/master/w_820,c_limit/long-beach-island-GettyImages-173005802.jpg', 'Long Beach Island, NJ', 'Long Beach Island (or LBI to the locals) is where Jersey Shore natives go to vacation, bouncing from northern beaches to this slightly more southern barrier island that competes with Cape Code and the Outer Banks. Though numbers swell in the summer, the beaches are wide and welcoming—and it\'s great place to learn how to surf.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Spring Lake', 'https://media.cntraveler.com/photos/5772c209c06bba921a97a124/master/w_820,c_limit/spring-lake-GettyImages-200148993-001.jpg', 'Spring Lake, NJ', 'This tony seaside town is just south of New Jersey\'s own \"Lake Como\" (to give you a sense of the vibe). It\'s a quieter beach, the antithesis to hard-partying Seaside Heights, and a prime spot to rent a home for the summer with a few friends or family');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Ocean Grove', 'https://media.cntraveler.com/photos/5772c208558ff1e22af127d3/master/w_820,c_limit/ocean-grove-alamy-F8W73G.jpg', 'Ocean Grove, NJ', 'This quaint Victorian town is quite the charmer. Once known as a summertime religious retreat, it’s now home to a large LGBT community—and who could blame the crowds for flocking here? Nagles Apothecary Café has some of the best ice cream and burgers around, and the beach is rarely overcrowded.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Avalon', 'https://media.cntraveler.com/photos/5772c205c06bba921a97a122/master/w_820,c_limit/avalon-GettyImages-122675152.jpg', 'Avalon, NJ', 'A little more secluded than its Seven Mile Island neighbor, Stone Harbor, this stretch of sand is known for its tucked away mansions, preppy adolescents, and generally well-heeled guests. Don’t blink if you see diamonds and designer swimwear during your morning laps.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Margate', 'https://media.cntraveler.com/photos/5772c2064a3399cb31f9da9e/master/w_820,c_limit/margate-alamy-EYBX4K.jpg', 'Margate, NJ', 'At just a mile and a half long and a mile wide, the immaculate Margate beach is an excellent alternative to the maxed-out sands of nearby Atlantic City—and among the masses of families, teenagers, and lone tanners, you can almost always find a spot to raise your umbrella. Make time to try the fried lobster tail at local favorite Steve & Cookie’s By the Bay.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Sandy Hook', 'https://media.cntraveler.com/photos/5772c2094a3399cb31f9da9f/master/w_820,c_limit/sandy-hook-GettyImages-478808527.jpg', 'Sandy Hook, NJ', 'Sandy Hook is part of the Gateway National Recreation Area, and the northernmost point of the Jersey Shore, which makes it a top destination for Manhattanites fleeing the city on a smoldering weekend. For good reason: There is a beach for every type (surfers, families, those in the buff); a bayside stretch for kitesurfing; and a great, long pathway for cycling.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Stone Harbor', 'https://media.cntraveler.com/photos/5772c20ac06bba921a97a125/master/w_820,c_limit/stone-harbor-GettyImages-514098089.jpg', 'Stone Harbor, NJ', 'Top-notch ice cream at Springer’s (try ‘Emotionally Nuts’), three different rooftop mini golf courses, and a downtown thick with upscale fashion and five-and-dimes—plus the local Wetlands Institute where you can sneak in some summer learning—make this blip near the end of the Garden State Parkway an ideal family-friendly destination.');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Point Pleasant', 'https://media.cntraveler.com/photos/5772c208c06bba921a97a123/master/w_820,c_limit/point-pleasant-alamy-E8PD0P.jpg', 'Point Pleasant, NJ', 'Those in the know skip Seaside and head to the slightly more low-key boardwalk attractions at Point Pleasant. You can get your Skee-Ball and salt water taffy fix without feeling like you\'re reliving an episode of Jersey Shore. ');
INSERT INTO `marka_db`.`beaches` (`beach_name`, `beach_img`, `beach_location`, `beach_desc`) VALUES ('Wildwood', 'https://media.cntraveler.com/photos/5772c20a4a3399cb31f9daa0/master/w_820,c_limit/wildwood-alamy-F4F0X0.jpg', 'Wildwood, NJ', 'The town’s retro hotels, billed by gaudy neon signs, might be a little too kitschy for some—but with a massive boardwalk that houses more than 100 rides and attractions, we’d be hard-pressed to take a pass on a night here. Just skip that cotton candy before a ride on the adrenaline-pumping Slingshot.');


